server:
  port: 8888

management:
  security:
    enabled: false

spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/git/workshop-microservices/labs/cloud-05/config-repo