server:
  port: 8888

management:
  security:
    enabled: false

spring:
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          uri: file:///${user.home}/Documents/Treinamento/Microservices/Labs/spring-cloud/lab6/config-repo
